### ISSUE TITLE
Import directory to ESPHome

### ISSUE THREAD

**Issue by zamzon** [majkrzak/esphome_ptm215b#1]
Hi
It doesn't seem to find the platform: ptm215b

How do I add your code in to my ESPHome device?

**Comment by majkrzak** [comment]
Looks like esphome expects repository with component to contain the `components/<name>` directory. I personally don't like such unnecessary verbosity. I've added the symlink, so now it should be possible to include it by:

```yaml
external_components:
  source: github://majkrzak/esphome_ptm215b
```

**Comment by zamzon** [comment]
Hi

I get this error, what do i need to insert under a0,a1,b0,b1
I could you give an example how to write something, ex. turn on a switch on A0 and off on A1

![Udklip](https://user-images.githubusercontent.com/12298056/214126257-11ad2dbf-37b6-45a5-a12c-6f411b5f60cc.PNG)

**Comment by majkrzak** [comment]
Each of those are binary sensors exposed by the module. You can follow the esphome documentation about them: https://esphome.io/components/binary_sensor/index.html

In short:
```yaml
any:
  on_press:
    then:
    - logger.log: "Hello World"
```

**Comment by zamzon** [comment]
thanks, it works.

did you include long press in the code?

**Comment by majkrzak** [comment]
This is out of scope of this implementation. It should be possible to achieve it with proper configuration of `on_click` automation in the binary sensor.
